### ISSUE TITLE
Timeout doesn't run with alias of a command

### ISSUE THREAD

**Issue by timur-g** [pshved/timeout#23]
Useful script, thanks. Could someone explain why it doesn't work as follows.

I use alias to determine folder, and that works when used alone (OK, I just realized it has wrong quotes, but it shouldn't be the reason of this problem):
alias sof="\$( if [[ -d folder1 ]] ; then echo folder1 ; else if [[ -d folder2 ]] ; then echo folder2 ; fi ; fi )/program --option"

I run program using that alias to open a file  (with timeout script renamed to tmt):
tmt sof file.ext

I get:
Can't exec "sof": No such file or directory at /usr/local/bin/tmt line 100.
Couldn't exec sof file.ext: No such file or directory at /usr/local/bin/tmt line 100.

Why tmt runs when full path of program is specified and not with alias?

**Comment by pshved** [comment]
Hi, thanks for reaching out!

You're right, the script wouldn't execute your bash alias correctly.  The script uses `exec @ARGV` to run the command.  This tries to find the executable you specified in the paths listed in the $PATH env variable. However, the alias `sof` is not an executable file; it is something internal to the specific shell you're using.

In order to execute that, you should run your shell explicitly and supply your alias as an argument.  something like this should work:

    tmt bash -c 'sof file.ext'

If your alias doesn't work, it is perhaps that the script where it's defined is not invoked when the shell is run via `bash -c`.  Please refer to `man bash` and the section "INVOCATION".

HTH,
Paul

**Comment by timur-g** [comment]
Thanks. That with bash -c  didn't work for me. 

But I found this: if alias is defined as global in Zsh (`alias -g sof=` ), tmt works there as long as there's single alias to start command: `tmt sof file.ext`.
It doesn't work if there are additional parameters like: `tmt pre-sof-param sof file.ext` (it doesn't works also if alias sof is replaced with full command, unlike `time pre-sof-param sof file.ext` which works).
